name: sanofi_evelyn
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.5.1
  firebase_messaging: ^14.1.5
  device_calendar: ^4.0.0
  googleapis: ^11.0.0
  google_sign_in: ^6.1.0
  fl_chart: ^0.35.0
  qr_code_scanner: ^1.0.0
  camera: ^0.10.0+4
  animated_bottom_navigation_bar: ^1.0.0+1
  local_auth: ^2.1.3
  signature: ^4.0.0
  pdf: ^3.7.0
  qr_flutter: ^4.0.0
  http: ^1.2.1  # Atualizado para uma versão mais recente compatível
  http_parser: ^4.0.0
  mime: ^1.0.0
  app_links: 3.4.1
  app_links_platform_interface: 1.1.0
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  collection: 1.18.0
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  functions_client: 1.3.2
  go_router: 12.1.3
  google_fonts: ^6.1.0
  gotrue: 1.12.6
  hive: 2.2.3
  intl: ^0.19.0  # Atualizado para compatibilidade
  json_path: 0.7.2
  fluttertoast: ^8.0.9
  lottie: ^1.0.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  modal_bottom_sheet: ^2.0.0 
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  percent_indicator: 4.2.2
  permission_handler: 11.3.0
  postgrest: 1.5.2
  provider: 6.1.2
  flutter_native_splash: ^2.0.5
  realtime_client: 1.4.0
  rxdart: 0.27.7
  flutter_launcher_icons: ^0.9.2
  firebase_messaging_web: ^3.5.18
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.6
  storage_client: 1.5.4
  supabase: 1.11.11
  supabase_flutter: 1.10.24
  table_calendar: ^3.1.0 # Atualizado para a versão mais recente compatível
  timeago: 3.6.1
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  webview_flutter: 4.7.0
  webview_flutter_android: 3.15.0
  webview_flutter_platform_interface: 2.10.0
  webview_flutter_wkwebview: 3.12.0
  geolocator: ^13.0.1

dev_dependencies:
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

# Configuração para flutter_native_splash
flutter_native_splash:
  color: "#ffffff"  # Cor de fundo da splash screen
  image: assets/images/logo-sanofi.png  # Caminho da imagem que você quer usar na splash screen
  android: true
  ios: true
  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"